name: Semantic Versioning

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  semver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine next version
        id: semver
        run: |
          # Get latest tag
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $TAG"

          # Default to 0.0.0 if no tag exists
          if [ -z "$TAG" ]; then
            TAG="0.0.0"
          fi

          # Split into parts
          IFS='.' read -r MAJOR MINOR PATCH <<< "$TAG"

          # Decide what to bump based on commit messages
          COMMITS=$(git log --format=%s $(git describe --tags --abbrev=0)..HEAD)

          if echo "$COMMITS" | grep -q "#major"; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif echo "$COMMITS" | grep -q "#minor"; then
            MINOR=$((MINOR + 1))
            PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi

          NEW_TAG="$MAJOR.$MINOR.$PATCH"
          echo "Next version: $NEW_TAG"

          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        if: steps.semver.outputs.new_tag != ''
        run: |
          git tag ${{ steps.semver.outputs.new_tag }}
          git push origin ${{ steps.semver.outputs.new_tag }}
